### ISSUE TITLE
[Packaging] Make this program available as flatpak in FlatHub

### ISSUE THREAD

**Issue by Nokia808** [nroduit/Weasis#130]
Hi. It will be very helpful for Linux user if you make this program available as flatpak package on FlatHub. By this you will make it available for almost all Linux distros.

1. home page of FlatHub is:
    https://www.flathub.org/home
2. FlatHub repositories are at:
    https://github.com/flathub
3. when some one like to add package to FlatHub, she/he need to open PR at:
    https://github.com/flathub/flathub/pulls
4. FlatHub differ from snap by being allow any one to package not only developers of packages. So packages on FlatHub are of 2 kinds regarding this point: some are packaged by their developers like qTox, Retroshare, Session, while others are packaged by persons other than their developers.
5. all packages on FlatHub are signed .....
6. even if person other than the original developer(s) maintain the package on FlatHub, FlatHub team try as much as possible to make developer(s) authorized to repositories at least to monitor & follow up the packaging ......
7. FlatHub allow both open & closed source packages. But regarding open source packages, the FlatHub team insisting on packager to make them deterministic (reproducible).

**Comment by alcir** [comment]
@nroduit For your information, this is my effort https://github.com/flathub/flathub/pull/2703
Sadly I'm not an expert of java and the like, so maybe something could be done better.

**Comment by nroduit** [comment]
Here are my recommendations to create a package:

- The build should use the package-weasis.sh script without the installer build (set the PACKAGE variable to FALSE) in order to:
  1. Package the application with the necessary Java Runtime modules (using jlink and [jpackage](https://docs.oracle.com/en/java/javase/17/jpackage/packaging-overview.html)). 
  2. Do not use viewer-linux.sh because the weasis-portable will disappear with the future Weasis 4.0. It should use weasis/bin/Weasis.
  3. Build package for different architectures (linux/amd64, linux/arm64, linux/arm/v7)
- Replace features of the installer: 
  1. Add the URLWhitelist for chrome and chromium (see in script/resources/linux/weasis.spec)
  2. Install shortcuts Weasis.desktop and Dicomizer.desktop 
  3. Register `x-scheme-handler/weasis;` and DICOM file associations for all users (by installing in /usr/share/applications/Weasis.desktop) . Don't know if it works for non-gnome distribution.

 I don't know if flatpak is similar to snap which forces sandbox mode. In this mode, Weasis won't be able to run because it doesn't have access to the $user/.weasis directory.

**Comment by alcir** [comment]
Thanks.
Roughly speaking, do you think that these steps are correct?

```text
mvn clean install
cd weasis-distributions && mvn clean package -Dportable=true -P compressXZ -Dmaven.repo.local=../.m2/repository
unzip weasis-distributions/target/portable-dist/weasis-portable.zip
sed -i 's/PACKAGE=YES/PACKAGE=NO/' weasis-distributions/script/package-weasis.sh
sed -i 's/curl.*/#&/' weasis-distributions/script/package-weasis.sh
weasis-distributions/script/package-weasis.sh --input . --output tmp --jdk ${JAVA_HOME}
mv tmp/Weasis/bin /app/
mv tmp/Weasis/lib /app/
```

**Comment by wcasanova** [comment]
It would be great to have version 4 in Flatpak/Flathub

**Comment by nroduit** [comment]
I have published [modifications](https://github.com/flathub/io.github.nroduit.Weasis/tree/beta) but a problem remains: the use of OpenJDK 18 is necessary for the final package. However, JDK 18 is not yet available as an extension (see [this pull request](https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk/pull/12)).  
Maybe it would be easier to download the JDK and put the path as the value of JAVA_HOME.

``` yml
    sources:
      - type: file
        only-arches:
          - x86_64
        url: https://github.com/adoptium/temurin18-binaries/releases/download/jdk-18.0.1%2B10/OpenJDK18U-jdk_x64_linux_hotspot_18.0.1_10.tar.gz
        sha256: 16b1d9d75f22c157af04a1fd9c664324c7f4b5163c022b382a2f2e8897c1b0a2
```
Some help is welcome

**Comment by alcir** [comment]
> I have published [modifications](https://github.com/flathub/io.github.nroduit.Weasis/tree/beta) but a problem remains: the use of OpenJDK 18 is necessary for the final package. However, JDK 18 is not yet available as an extension 

Let's wait that the PR will be merged.

**Comment by nroduit** [comment]
@alcir Currently, the compilation and Maven require Java 17 to be installed. Only in the last command of jpackage, Java 18 is required (only the path is necessary, not the installation). So that's why I tried to download Java 18, unpack it and give the path to the command, it should be enough.

**Comment by nroduit** [comment]
I finally found how to make a package with the latest version of Java, see https://flathub.org/apps/details/io.github.nroduit.Weasis
