### ISSUE TITLE
What does #1, #2, ... mean?

### ISSUE THREAD

**Issue by leonardorame** [nroduit/Weasis#138]
Hi, I noticed in some cases that series are splitted, and in the thumbnails appears a #1, #2, etc. as shown in this screenshot:

![image](https://user-images.githubusercontent.com/1405017/86931159-256fac80-c10e-11ea-8d82-b356230a091a.png)

What does those numbers mean?, when a series is splitted and why?.

**Comment by nroduit** [comment]
There are different reasons of splitting series because there are different values of image type, sop class UID, image orientation plane... within a series. You can override the default rules which are commented in this [file](https://github.com/nroduit/Weasis/blob/master/weasis-distributions/resources/series-splitting-rules.xml). See also how to [modify resources](https://nroduit.github.io/en/basics/customize/preferences/#customizeresources).

**Comment by leonardorame** [comment]
Great, I asked this because in my viewer (based on cornerstonejs) a recurring problem is the displaying of series containing different SOP Classes (for example US single frame + US multiframe).
