### ISSUE TITLE
Display order of "split series"

### ISSUE THREAD

**Issue by pacssee** [nroduit/Weasis#205]
When viewing multi-frame instances, the viewer nicely creates a series for each instance.
However, the order of these 'split series' is unclear. They are for sure not ordered by acquisition time which should be the default (The Radiologists / Cardiologists usually want to view the images in the same order they were acquired in).

There should be a setting for controlling the order of display of 'split series' or at least make the 'split series' respect the setting of "Sort Stack By" in the 2D viewer.

Especially important for viewing echocardiography studies.

**Comment by nroduit** [comment]
It is possible to [configure rules](https://nroduit.github.io/en/tutorials/dicom-explorer/#series-level) for the division of the series, but there are no parameters to manage the order of the sub-series.
Sub-series are sorted by the number assigned at the time of cutting. This number is simply generated in the processing order. It would be better to assign this number according to the acquisition time. However, it is not easy to manage this because the files can arrive in any order and moreover the download processes are asynchronous and parallelized in threads. So I have to check how to do it.
