### ISSUE TITLE
Separate "drawing tools" and "measurement tools" (chnage drawing icon)

### ISSUE THREAD

**Issue by pacssee** [nroduit/Weasis#206]
Users often get confused as to the difference between drawing tools and measurement tools. The icons are adjacent to each other and look similar (see image).
It would be a good idea to make them stand out and look different.

![image](https://user-images.githubusercontent.com/88653529/129891325-35eb347f-f1f4-428a-98dc-9d2ac6ef44ce.png)

**Comment by nroduit** [comment]
These 2 tools are grouped in the same toolbar because they belong to the same category of tools. They allow to see the default selection without having to open the right panel (especially when the "Draw only once" mode is deselected).
The icons are for me different and allow to see the selection for the drawing or the measurements. They have a similar color which could be changed to avoid this confusion.

![Sélection_121](https://user-images.githubusercontent.com/993975/130071252-63cafe69-c1f6-42d2-a1db-2452ea1e0d88.png)
