### ISSUE TITLE
About JDK11 For sun.misc.Signal  In WeasisLauncher.java

### ISSUE THREAD

**Issue by runqinshiye** [nroduit/Weasis#228]
weasis-launcher\src\main\java\org\weasis\launcher\WeasisLauncher.java:1261:42

private void registerAdditionalShutdownHook() {
    try {
      Class.forName("sun.misc.Signal");
      Class.forName("sun.misc.SignalHandler");
      **sun.misc.Signal.handle**(new sun.misc.Signal("TERM"), signal -> shutdownHook());
    } catch (IllegalArgumentException e) {
      LOGGER.log(Level.SEVERE, "Register shutdownHook", e);
    } catch (ClassNotFoundException e) {
      LOGGER.log(Level.SEVERE, "Cannot find sun.misc.Signal for shutdown hook exstension", e);
    }
  }

**Comment by nroduit** [comment]
What is the request or question?

**Comment by runqinshiye** [comment]
sun.misc.Signal is removed in jdk11; WeasisLauncher.java quoted  ‘sun.misc.Signa’。

![4EW@ZCBU(%W7 U_`%4$N~XC](https://user-images.githubusercontent.com/76540623/146336149-d172a5b8-1b60-4d96-952d-65af9cd05f29.png)

https://stackoverflow.com/questions/19711062/alternative-to-sun-misc-signal

**Comment by nroduit** [comment]
No this class still exist in the current openjdk => https://github.com/openjdk/jdk/blob/master/src/jdk.unsupported/share/classes/sun/misc/Signal.java

It is in jdk.unsupported package which is loaded by Weasis, see https://github.com/nroduit/Weasis/blob/ae3467de66008aaffd019c8a29c9f6cd7a85cfe9/.github/workflows/build-installer.yml#L66

This code exists because the switch of the Windows session kills the process without waiting to clean all the temp images.

**Comment by runqinshiye** [comment]
Thank you for your reply. I understand your design logic.
I solved this current compilation problem:
project use jdk11
![image](https://user-images.githubusercontent.com/76540623/146347786-6ebdac3b-842e-4876-979f-4be6fe881e0b.png)
and weasis-launcher use jdk8
![image](https://user-images.githubusercontent.com/76540623/146347855-bf171507-3275-4af9-a841-132e9f642e43.png)

thanks very much,your work is great.

**Comment by nroduit** [comment]
Yes, the compilation level is still java 1.8. Weasis 4 will move to Java 17.

**Comment by runqinshiye** [comment]
ok, Weasis 4 Native compilation is worth looking forward to.
