### ISSUE TITLE
All Patients option not shown in dropdown

### ISSUE THREAD

**Issue by amasmiller** [nroduit/Weasis#239]
It appears that the ability to display and use "All Patients" in DICOM explorer is in the source code, but may be unintentionally commented out?

It would be useful for us to display "All Patients", but this is only an option after I uncomment this line in the source:

`// modelPatient.insertElementAt(ALL_PATIENTS, 0);`
(https://github.com/nroduit/Weasis/blob/v3.8.0/weasis-dicom/weasis-dicom-explorer/src/main/java/org/weasis/dicom/explorer/DicomExplorer.java#L416)

If uncommented, the All Patients appears to work as expected:

![image](https://user-images.githubusercontent.com/32115401/151214353-e962dde6-1adc-4f2e-9f3e-826ed51b5850.png)

**Comment by nroduit** [comment]
This feature was intentionally commented because the main use of Weasis is as a clinical viewer and the separation in the display of the patients is essential. This feature has been removed in version 4 which brings a new design to the application.

One of the major problems is when you select a tab that cannot contain images/series of a patient then the patient in the explorer is selected.

**Comment by amasmiller** [comment]
Got it.  Thank you!  I'm good with closing this ticket.
