### ISSUE TITLE
Annotation View not exported

### ISSUE THREAD

**Issue by gsk1692** [nroduit/Weasis#293]
Hello,

First of all, thank you for creating a wonderful tool!

So I have imported some DICOM images. I have drawn annotations/boxes on one frame (say nth frame) of the DICOM image. However, when I am exporting as PNG, the annotation is stored as XML. But the drawing is not present in the nth frame PNG image.

I am aware of the export view option. But is there any other way to include this annotation in the PNG image itself while exporting as bulk? 

Thank you!

**Comment by nroduit** [comment]
It is not possible to include graphics into the image except with the export as Current View (like a screenshot). [Using DICOM Presentation State](https://nroduit.github.io/en/tutorials/build-ko-pr/), annotations can be shared and viewed with other viewers. For non-dicom, we use an xml file to preserve the image. Otherwise, it becomes image editing which is not the purpose of a viewer.

The[ release published yesterday](https://nroduit.github.io/en/getting-started/) fixes the issue of [rereading a non-dicom image with xml](https://github.com/nroduit/Weasis/issues/258).

**Comment by gsk1692** [comment]
Thank you for the information.

I understand that your point that this is not an image editor. However, just a feedback request for you to consider. If you can include a checkbox to export the view while exporting the DICOM images to other formats as bulk, it will be a boon to create and annotate datasets for CV tasks such as object detection. Kindly consider this as a future option to include. Thanks!
