### ISSUE TITLE
Display of graphic information from a DICOM Comprehensive SR with a multiframe series

### ISSUE THREAD

**Issue by seandoyle** [nroduit/Weasis#309]
I'm not sure if this is a feature request or a bug. I've been trying to load some SRs which contain graphic annotations (POLYLINE or CIRCLE).  The overlays are not displayed. I'm not sure that the SRs are correct (they pass the dciodvfy validator - so they are at least valid Part 10 files).

Clicking in the 'CIRCLE' or 'Show the image' links does bring me to the right image (actually - it brings me to the right frame since these are Enhanced MR images). 

I'm loading the files from disk using the Import DICOM button. 

I looked briefly in the source tree and see that ComprehensiveSRStorage and Comprehensive3DSRStorage are commented out in `./weasis-distributions/resources/store-tcs.properties`. Does this mean that rendering graphic overlays from these files is not implemented? If it should be - could you point out the area in the code where these are rendered so that I can adjust my SRs to render?  Or - if the problem is using Enhanced MR I can convert to the standard MR format (although Enhanced MR and GSPS work just fine). 

What I would like is for the SRs to be rendered the same way that the GSPS ones are rendered and for the links in the SR to display the particular item with the overlay graphics.

**Comment by nroduit** [comment]
If you want to add annotations, it is better to use DICOM PR instead of DICOM SR because the latter is much more limited for defining graphics. Some applications (like Osirix) generate annotations in DICOM SR but in a proprietary way.

However, it is possible to add SCOORD annotations in a DICOM SR but I notice that it does not work anymore in version 4. In version 3.8.1, you have to click on "Show the image" in the Findings section for the annotations to be displayed on the image. If this is not the case, you must send me an example.

![image](https://user-images.githubusercontent.com/993975/179389854-6b7ae6cd-bc9e-4312-8e29-91a5b955a2e6.png)

**Comment by nroduit** [comment]
I actually found a bug with a series containing several images. The association was always done on the first image of the series.
