### ISSUE TITLE
Cannot load image with weasis.war(v3.6.0) embed dcm4Chee_web3

### ISSUE THREAD

**Issue by mikite** [nroduit/Weasis#333]
As title describe, I use weasis.war to view image in dcm4chee_web3(v2.17.1).
error show in java application window, logs attached.
Any suggesstion to solve this? thanks in advance!

[weasis.log](https://github.com/nroduit/Weasis/files/9624555/weasis.log)

**Comment by nroduit** [comment]
Unfortunately dcm4chee 2.x.x is no longer maintained since 2015 and I can only encourage you to upgrade to dcm4chee-arc-light.
It seems to have several installation and/or configuration issues. You can still follow the installation documentation [here](https://nroduit.github.io/en/getting-started/dcm4chee/#for-dcm4chee-web3).

**Comment by mikite** [comment]
thanks for ur reply, 

> Unfortunately dcm4chee 2.x.x is no longer maintained since 2015 and I can only encourage you to upgrade to dcm4chee-arc-light. It seems to have several installation and/or configuration issues. You can still follow the installation documentation [here](https://nroduit.github.io/en/getting-started/dcm4chee/#for-dcm4chee-web3).

thanks for ur replay, I solved this by use the matched version of weasis.war and weasis client.
