### ISSUE TITLE
Loading a corrupt DICOM file should have visible error message

### ISSUE THREAD

**Issue by unsafeunaudited** [nroduit/Weasis#472]
### Is your feature request related to a problem? (optional)

I downloaded a DICOM image via email that seems to have a broken upload (from my usual workflow, confirmed broken with another DICOM View AlizaMD, showing a cut-off image).

Weasis does not seem to provide feedback from loading a broken DICOM file and just continues to run as if I did not load an image.

### Description of the new feature/enhancement

Should display a pop-up/notification warning stating that the file loaded is corrupt. 

### Proposed technical implementation details (optional)

Sorry I cant code. Will try to learn Java at least now I have a use case for learning a language.

### Describe alternatives you've considered (optional)

Display the cut-off image. The caveat could be a maliciously crafted DICOM file could enable arbitrary code execution. I don't know if that is an actual possibility.

### Additional context (optional)

On a Fedora 38, Wayland
I ran Weasis via terminal and captured the relevant output during loading the problematic DICOM image:

06.10.2023 13:58:31.794 *ERROR* [Dicom Model-pool-2-thread-1] org.weasis.dicom.codec.DicomMediaIO: Cannot read DICOM: java.io.EOFException
	at org.dcm4che3.util.StreamUtils.skipFully(StreamUtils.java:77)
	at org.dcm4che3.io.DicomInputStream.skipFully(DicomInputStream.java:490)
	at org.dcm4che3.io.DicomInputStream.createBulkData(DicomInputStream.java:778)
06.10.2023 13:58:31.827 *INFO* [AWT-EventQueue-0] org.weasis.dicom.explorer.LoadDicom: End of loading DICOM locally

**Comment by nroduit** [comment]
We produce error messages when the image is corrupted or essential DICOM fields cannot be read (See https://github.com/nroduit/Weasis/issues/175#issuecomment-778167701), but if the DICOM structure itself is not readable then there are no messages apart from log traces.

In this case, the file is considered non-parsable by the dcm4che toolkit and we don't display a message because there can be any kind of file in the directories and the DICOM files don't necessarily have an extension and a magic number. In short, displaying this kind of message could have more negative than positive effects for the user.

When using Weasis with a DICOM archive server, there may be network interruptions that corrupt the file, in which case a message is displayed to try to re-download the missing files. See https://groups.google.com/g/dcm4che/c/_mMylnYnirc/m/lQ6IW_K_BAAJ

**Comment by unsafeunaudited** [comment]
I do not have a proper perspective of a programmer right now (I seek to change this in the future) but do understand that when the radiologist load 20+ files, they might not manually count the patients loaded.

What might happen is that, the radiologist might miss some of patients for reading at best. At worst a false normal interpretation might happen and be released as an official result.

On a flawed workflow:

1. A radiologist could just copy the patient list from the operating system's file manager/explorer.
2. Paste the list in a document/text editor.
3. Switch back to the file manager to highlight and load/open all of the patients.
4. Close the normal looking patient images
5. Switch to a document/text editor to type the patient with abnormal finding.
6. Go back to step 4 until the patient list for interpretation is consumed/finished.

In the above workflow, without displaying any error messages, the radiologist could miss out a patient with a problematic DICOM image that is non-normal and release the official result as normal.

With an error message at the end of loading a batch of DICOM image, the radiologist could go back and re-check/re-count or maybe open the files individually instead of just a normal reading workflow. A simple but vague message stating that "Potential issues encountered during loading of patients" could be valuable to the end user of Weasis.

I do also realize that there should also be due diligence on the side of radiologist using the app. I do hope you will have find value in this insight.

Thank you again.

**Comment by nroduit** [comment]
In my career, I have never seen in a professional environment the use case you describe where a radiologist would copy files to his workstation to view them. Files are always centralized in an archive.
Weasis is a viewer that is usually connected directly to a DICOM archive. As mentioned above, if the structure of the DICOM file itself is corrupted, then the file cannot be stored in a DICOM archive, nor can it pass through the DICOM interoperability services.

The use cases where Weasis is used in standalone mode are mainly for reading CDs or USB keys, which usually contain a single patient. In the circumstance that some files cannot be read, and if these media respect the DICOM standard of having a DICOMDIR file, then there will be a message in Weasis to indicate that certain files cannot be read (as the DICOMDIR is a register of the media content). Same if you download a DICOM ZIP.

**Comment by unsafeunaudited** [comment]
Greetings!

I understand that I may be a corner case but I would just like to add that what you have described above is for systems with a competent IT department that could properly set up a DICOM server to send images directly to Weasis.

Meanwhile the rest of the (third) world, particular in the island provinces,  with either absent, incomplete or incompetent IT infrastructure, I am forced to adapt and accept emails (sent by RadTechs with minimal tech savviness ) with attached .jpg files, compressed collection of DICOM files, and on this particular use case: DICOM files that was directly attached to an email, and then downloaded to a local folder to be read on a batch by batch basis (usually of 20+ images).

My work around for this is to read with a smaller batch (by 5s instead of 20s) where I could visually check that all files were loaded.

I think I am ready/prepared to close this issue (as not planned?), unless you plan to add a notification or propose a different solution (that I would be thankful for).

**Comment by nroduit** [comment]
I understand that you're doing what you can in your own context. Unfortunately, I can't encourage the use of this type of workflow because it doesn't respect basic good security and confidentiality practices.

Unfortunately, I don't have a simple solution to improve the way you work. Having taken part in several humanitarian projects to install PACS, I fully understand the difficulty of setting up all this infrastructure without costs escalating, and maintaining it. However, I think it's possible to develop skills in open source tools and expertise in medical standards because all this is available on the Internet with an active community. It's a fundamental change that needs to be made over the long term, by investing in education and the attractiveness of these new professions.

**Comment by unsafeunaudited** [comment]
I was given the choice by those in charge that the option was it either print in bond paper (non-diagnostic), send as .jpg (also non-diagnostic) or send as DICOM.

I too wanted to do better with regards to privacy and security but sometimes you are just given things to deal with. I will try the USB workflow or maybe I could persuade them to let me connect my local Weasis to their server.

Thank you for your response and your time.

**Comment by nroduit** [comment]
[I'll add an error message ](https://github.com/nroduit/Weasis/issues/479)but I'm not 100% sure it will cover the problem described here.
