### ISSUE TITLE
After the dicom image is moved, the position of the image will return to the original position.

### ISSUE THREAD

**Issue by a347807131** [nroduit/Weasis#474]
## here's the actions

1. pan the imge
   ![image](https://github.com/nroduit/Weasis/assets/24996382/09060f60-ce31-47f2-a7ba-542c4122b408)

2. scroll the series

![image](https://github.com/nroduit/Weasis/assets/24996382/6984486d-9188-4f7e-bdf5-aee17ad822a4)

the dicom image's position will get to the center of viewer ater scrolling the series, while it dont come out when i do the same actions after zooming it.

### What version of Weasis are you running?

4.2.0

### On which system the problem occurs?

Windows

**Comment by nroduit** [comment]
Please read this https://github.com/nroduit/Weasis/issues/328#issuecomment-1241542986
When the zoom is in best-fit mode, then it's normal behavior to recenter the image. As soon as the zoom is changed, the PAN position is preserved. A new view is in best-fit mode by default. MPR views, on the other hand, are not.

@AlexZaka Please do not add new problems that are not directly related. DICOM Print works in a very basic mode due to the lack of standardization among suppliers. See https://groups.google.com/g/dcm4che/c/XNdFiyd9SfU/m/eEz2Q6DwAgAJ

**Comment by a347807131** [comment]
well, my bad .
