### ISSUE TITLE
Hidden thumbnails of a study

### ISSUE THREAD

**Issue by Giovanni-G** [nroduit/Weasis#584]
### Describe the bug. What happened?

If a study has more than 15 series, only the thumbnails of the first 15 series appear on the left bar.
To view the hidden series image I have to select the last series, press the keyboard down arrow key and then press Enter, but the thumbnail remains hidden.

### What version of Weasis are you running?

4.5.0

### On which system the problem occurs?

Windows, Linux

**Comment by nroduit** [comment]
Please provide more information to reproduce the issue because I have tried with studies having more than 30 series and have not observed a problem.

**Comment by Giovanni-G** [comment]
I did more testing: the bug appears only if the number of series is exactly 16.
If you have a study with 17, there is not problem.

This is a study with 16 series but I can see only 15 thumbnails.
![Weasis 1](https://github.com/user-attachments/assets/36775a8f-46cc-47c7-b2a8-e77164609ce2)


To view the series 16, I have to use the keyboard: from last series I press "down" and then "enter".
The image appears but the thumbnail remains hidden.
![Weasis 2](https://github.com/user-attachments/assets/cd772158-f346-4e0f-8d27-bbea240a464d)

**Comment by nroduit** [comment]
I've tried it exactly with 16 series and I don't see the problem.

There was a [thumbnail display bug](https://github.com/nroduit/Weasis/issues/443) in a previous version. You can try maximizing the Dicom Explorer window and see if the missing thumbnail is displayed.

Otherwise, it could be a metadata inconsistency problem. [Activate the logger](https://weasis.org/en/tutorials/logging/) in debug mode and check for a WARN/ERROR when loading data. If no issue is found, you'll need to provide a dataset to reproduce the problem.

**Comment by Giovanni-G** [comment]
Thank you for the reply.

Changing the size of Dicom Explorer windows, the missing thumbnail is displayed.
The log file is free from warn/error.

Anyway with the new version (4.5.1), the problem disappears from both my pc (fedora workstation and windows 10).
