### ISSUE TITLE
Does not build with OpenJDK Java 11

### ISSUE THREAD

**Issue by zacmar** [nroduit/Weasis#70]
Maven build fails when using OpenJDK Java 11.

1. Follow build instructions at https://nroduit.github.io/en/getting-started/building-weasis/

Expected Behaviour:
The instruction state that JDK 8 or higher is needed and makes no mention that JDK 11 will not work. Hence I expected the build to not fail with JDK 11.

 - OS: Manjaro Linux
 - Weasis Version: 3.0.4

Traces
[error.log](https://github.com/nroduit/Weasis/files/3073524/error.log)

**Comment by nroduit** [comment]
Yes, you cannot build the version 3.0.x with OpenJDK 11 because there are a lot of [removed APIs](https://www.oracle.com/technetwork/java/javase/11-relnote-issues-5012449.html#Removed), especially jaxb which is used for the graphics persistence.

The version 3.5.x requires at least Java 9 (from 9 to 13)  for compilation but produce jars compliant with Java 1.8 to Java 13.
